name: susanlee
favicon: null
layout_spectrum: 0.2465958148241043
typography_spectrum: 0.05026575643569231
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.29984289570711553
  lightness: 0.042586991330608726
  saturation: 0.6560399399604648
  rhythmicContrast: 0.34758009295910597
purpose: []
